## WTF!?
# baseURL is a question. Currently the blog resides at
# https://smallcultfollowing.com/babysteps/
#
# Since it appears that smallcultfollowing.com isn't being
# used I would just move the blog there.
#
# If you want the domain for something else, and/or want to
# keep the babysteps blog name going...
#
# 1) Move the blog to the root of `babysteps.smallcultfollowing.com`
# 2) Move the blog to the root of `baby-steps.smallcultfollowing.com`
#
# Either way having the site served from a path isn't exactly
# friendly.
##
baseURL = '/'
disablePathToLower = true
removePathAccents = true
languageCode = 'en-us'
title = 'Baby Steps' # TBD?
theme = 'm10c'

[author]
  name = 'Niko Matsakis'
  email = 'niko@alum.mit.edu'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[permalinks]
[permalinks.page]
  'blog' = "/blog/:year/:month/:day/:slug/"
[permalinks.section]
  'blog' = "/blog/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"

[params]
  author = 'Niko Matsakis'
  description = 'This blog is where I post up various half-baked ideas that I have.'
  avatar = 'https://smallcultfollowing.com/babysteps/assets/daphne.png'

[[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/nikomatsakis"
[[params.social]]
  icon = "twitter"
  name = "Twitter"
  url = "https://twitter.com/nikomatsakis"
[[params.social]]
  icon = "rss"
  name = "RSS"
  url = "/index.xml"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"